### ISSUE TITLE
[QUESTION] Ubuntu 14.04 Compatibility

### ISSUE THREAD

**Issue by akafael** [dqrobotics/cpp#20]
## Bug description

I am unable to compile at Ubuntu 14.04 due to minimum cmake version requirement.

### Hotfix:
It was quite simple to solve. I just changed from 3.4 to 2.8 as show bellow and worked just fine.

https://github.com/dqrobotics/cpp/blob/c2154c0cc5ac2ee8ca30cae41c8798245950dfc8/CMakeLists.txt#L1

To 

```
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
```

Then I tested using travis for manual compilation with something like:

```
language: generic
matrix:
  include:
  - name: "Trusty indigo"
    dist: trusty
  - name: "Trusty jade"
    dist: trusty
  - name: "Xenial kinetic"
    dist: xenial

before_script:
  - sudo apt-get install -y cmake libeigen3-dev # DQRobotics

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
```

To ensure it would not have any trouble.

### Environment:
 - OS: [Ubuntu 14.04, ,Ubuntu 16.04, Ubuntu 18.04]
 - dqrobotics current
